{
    "name": "Hospital Management ",
    "author": "Sakshi",
    "license":"LGPL-3",
    "version": "18.0.1.0",
    "category": "Hospital",
    "sequence": -100,
    "summary": "Hospital Management System",
    "depends": ['mail','product','base','sale'],
    "data": [
             'security/groups.xml',
             'security/ir.model.access.csv',
             'report/appointment_report_templates.xml',
             'report/patient_history_report.xml',
             'report/prescription_report.xml',
             'wizard/cancel_appointment_view.xml',
             'wizard/prescription_view.xml',
             'data/sequence.xml',
             'views/operation_view.xml',
             'views/patient_view.xml',
             'views/appointment_view.xml',
             'views/doctor_view.xml',
             'views/ir_cron_data.xml',
             'views/email_template_view.xml',
             'views/menu.xml',
             # 'views/res_config_settings_views.xml',
            'views/resuchedule_template_controllers.xml',            ],
    "demo": [],
    "application": True,
    "auto_install": False,

}
